db:
  postgres: 
    uri: postgres://pipi:sasa@localhost:5432/application_form
    heroku: postgres://sizufkfijeumaz:a3f6da68daaaa8cc5109bfbd423ff21e7373ccab565fc38e62f1e64dafce56f2@ec2-3-215-40-176.compute-1.amazonaws.com:5432/ddfa3qgp8gjdgt

  mongo: 
    uri: mongodb+srv://pipi:dDOi7wfc3DLqmxK2@cluster0.han2q.gcp.mongodb.net/application_platform?retryWrites=true&w=majority

admin:
  cookie_secret: TRVYqmENPKRyQZrTAzm7D7ykCJtwVvp5aPvcrSY66FgYesdHzq

google:
  sheets:
    application: 1N_j5vx1Ux4AvDruZOPpjB5j5Zsen8DLe0A6YUdGl6ks
    videoAsk: 1ux8oNKN9LNPbQEHm70N_Vco3dDAuYfKe1gg0XOtA3Lw